WebsiteApplication/Controllers/AdditionalControllers/CultureController.cs
using System;
using System.Web;
using System.Web.Mvc;
using WebsiteApplication.CodeBehind.Helpers;

namespace WebsiteApplication.Controllers.AdditionalControllers
{
    public class CultureController : Controller
    {
        [HttpPost]
        public ActionResult SetCulture(string culture)
        {
            culture = CultureHelper.GetImplementedCulture(culture);
            var cookie = Request.Cookies["_culture"];
            if (cookie != null)
                cookie.Value = culture;
            else
                cookie = new HttpCookie("_culture")
                {
                    Value = culture,
                    Expires = DateTime.Now.AddYears(1)
                };
            Response.Cookies.Add(cookie);

            return Json("");
        }
    }
}

WebsiteApplication/Views/Shared/_CultureSelector.cshtml
@using System.Threading
@using WebsiteApplication.Models.ViewModels.Home
@{
    var culture = Thread.CurrentThread.CurrentUICulture.Name;
    @Html.Kendo().Culture(culture)
}

<script id="cultureTemplate" type="text/x-kendo-template">
    <div style="display: block; text-align: right;">
        <span>#=data.CultureFullName#</span>
        <span>
            <img src="/Content/Images/flag-#=data.Flag#.png" />
        </span>
    </div>
</script>

<div>
    <ul class="nav navbar-nav" style="margin-top: 7px;">
        <li>
            @(Html.Kendo().DropDownList()
                  .Name("cultureSelector")
                  .HtmlAttributes(new {style = "width: 130px"})
                  .Events(e => e.Change("onChange"))
                  .DataTextField("CultureFullName")
                  .DataValueField("CultureId")
                  .TemplateId("cultureTemplate")
                  .ValueTemplateId("cultureTemplate")
                  .BindTo(new List<CultureListItem>
                  {
                      new CultureListItem
                      {
                          CultureId = "pl-PL",
                          CultureFullName = "Polski",
                          Flag = "pl"
                      },
                      new CultureListItem
                      {
                          CultureId = "en-GB",
                          CultureFullName = "English",
                          Flag = "uk"
                      }
                  })
                  .Events(e => e.DataBound("setCurrentCultureFlag")))
        </li>
    </ul>
</div>

<script>
    function onChange(e) {
        var value = $('#cultureSelector').val();
        $.post("@Url.Action("SetCulture", "Culture")",
            { culture: value },
            function(result) {
                window.location.reload();
            });
    }

    function setCurrentCultureFlag(e) {
        $('#cultureSelector').data('kendoDropDownList').value('@culture');
    }
</script>

WebsiteApplication/Views/Shared/_KendoHorizontal.cshtml
@using WebsiteApplication.CodeBehind.Extensions

@(Html.Kendo().Menu().Name("horizontal-menu")
        .Items(i =>
        {
            i.Add().Text("Dashboard").Action("Index", "Dashboard");
            i.Add().Text(GlobalTranslations.Institutions).Action("Index", "Institution").Visible(ApplicationPrincipal.IsInAnyRole("ADMIN,ADMIN_TECH,TECHNICAN"));
            i.Add().Text(GlobalTranslations.RolesAndRights).Action("Index", "Rights").Visible(ApplicationPrincipal.IsInRole("ADMIN"));
            i.Add().Text(GlobalTranslations.Reports).Items(inner =>
            {
                inner.Add().Text(GlobalTranslations.Mine).Action("MineReportsList", "MineReportsList").Visible(ApplicationPrincipal.HasRight("REPORT_GENERATION"));
                inner.Add().Text(GlobalTranslations.ToAcceptance).Action("ReportsList", "ReportsList").Visible(ApplicationPrincipal.HasRight("REPORT_ACCEPTANCE"));
            }).Visible(ApplicationPrincipal.HasRight("REPORT_GENERATION"));

            i.Add().Text(GlobalTranslations.Patients).Items(inner =>
            {
                inner.Add().Text(GlobalTranslations.SearchPatient).Action("Index", "Patient");
            }).Visible(ApplicationPrincipal.HasRight("GET_PATIENT_INFO"));
            i.Add().Text(GlobalTranslations.AboutSystem).Action("About", "Home");
            i.Add().Text(GlobalTranslations.Contact).Action("Contact", "Home");
            i.Add().Text(Html.Partial("_LoginPartial").ToHtmlString()).Encoded(false).HtmlAttributes(new {@style = "float: right;" });
        }))


    @if (Request.IsAuthenticated)
    {
        <script>
            $(function() {
                var item = $('.k-item.k-state-default.k-last').last()[0];
                item.firstChild.style.display = "none";
                item.append($('#logoutForm')[0]);
            });
        </script>
    }
    else
    {
        <script>
            $(function() {
                var item = $('.k-item.k-state-default.k-last').last()[0];
                item.firstChild.style.display = "none";
                item.append($('#loginContainer')[0]);
            });
        </script>
    }

WebsiteApplication/Views/Shared/_Layout.cshtml
@using WebsiteApplication.CodeBehind.Extensions
<!DOCTYPE html>
<html lang="pl-PL">
<head>
	<meta charset="utf-8"/>
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>@ViewBag.Title - MGR</title>
	@Styles.Render("~/Content/css")
	@Styles.Render("~/Content/kendo/css")
	@Scripts.Render("~/bundles/modernizr")
	@Scripts.Render("~/bundles/jquery")
	@Scripts.Render("~/bundles/kendo")
	
	<style>
		.d-logout > i {
			float: right;
		}
	</style>

	<meta name="description" content="Praca magisterska - Rafał Kamil Palej"/>
	<script src="@Url.Content("~/Scripts/kendo/jszip.min.js")"></script>
</head>
<body>
<script>
	var app = app || {};
	app.register = function(ns, o, init) {
		var tmp = window;
		ns.split('.').map(function(x) {
			!tmp[x] && (tmp[x] = {});
			tmp = tmp[x];
		});
		$.extend(tmp, o);
	};
	app.notify = app.notify ||
	(function() {
		return $('<div/>').kendoNotification({
			width: '80%',
			stacking: "down",
			position: {
				pinned: true,
				top: 30,
				right: 20
			},
			show: function(e) {
				e.element.parent().css('zIndex', 99999);
				if (e.sender.getNotifications().length === 1) {
					var element = e.element.parent(), eWidth = element.width(), wWidth = $(window).width(), newLeft;
					newLeft = Math.floor(wWidth / 2 - eWidth / 2);
					e.element.parent().css({ left: newLeft });
				}
			}
		}).data('kendoNotification');
	})();
</script>
<div class="container">
	<div class="row">
		<div id="nav-wrapper">
			@Html.Action("Menu", "Menu")
		</div>
	</div>
</div>
<div class="container body-content">
	@RenderBody()
	<hr/>
	<footer>
		<p>&copy; @DateTime.Now.Year - Rafał Kamil Palej - AGH</p>
	</footer>
</div>

@(Html.Kendo().Notification().Name("popupNotification"))

@Scripts.Render("~/bundles/bootstrap")
@RenderSection("scripts", false)

</body>
</html>